version: '3.8'

services:
  lead-management-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=72.61.238.231
      - DB_PORT=5437
      - DB_USER=leadmanagementadmin
      - DB_PASSWORD=sparshjain@28
      - DB_NAME=leadmanagement
      - JWT_SECRET=leadmanagement_secret_key_2024
      - PORT=3000
      - API_URL=http://cardapi.finonest.com
    restart: unless-stopped